// app/layout.tsx

import type { Metadata } from "next";
import { Lexend, Raleway } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { NavBarWrapper } from "@/components/NavBarWrapper"; 
import { ThemeInit } from "../../.flowbite-react/init";
import { FooterBottom } from "@/components/Footer";


const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${raleway.variable} antialiased font-light`}
      >
        <ThemeInit /> 
        
  
        <Providers>
          <NavBarWrapper /> 
          {children}
        </Providers>
        <FooterBottom />
      </body>
    </html>
  );
}